### PR TITLE
Use a function to enable debug logs on Android

### LINKED ISSUE #250: debugAttach fails on Android with new clang versions
On Android, `util.h` defines `boolean debugAttach;`, and that header is added to all services.
When linking those services, this exception is thrown:
```
[INFO] ==================== LINK TASK ====================
[INFO] [SUB] ~/.gluon/substrate/Android/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.gold: error: /Sample/target/client/aarch64-android/gvm/lib/libutil.a(util.o): multiple definition of 'debugAttach'
[INFO] [SUB] /~/.gluon/substrate/Android/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.gold: /Sample/target/client/aarch64-android/gvm/lib/libaccelerometer.a(accelerometer.o): previous definition here
```

This happens with clang 11.0.5, but not with older versions (9.0.8)

We need to move the constant `debugAttach` to a function `isDebugAttach()`.

### PR DESCRIPTION
**Pull request by jperedadnr**
Fixes #250

### CODE REVIEW

File: modules/util/src/main/native/android/c/util.h [hunk 1]
```diff
@@ -41,4 +41,4 @@ JavaVM* getGraalVM();
 
 jclass substrateGetUtilClass();
 
-jboolean debugAttach;
```
Comment (johanvos) [inline modules/util/src/main/native/android/c/util.h:44]: still need to include a guard in this file, e.g. #ifndef ATTACH_UTIL

Comment (jperedadnr) [reply modules/util/src/main/native/android/c/util.h:44]: Done

**Review by johanvos — APPROVED** [review]
