### PR TITLE
Use global variable for clipboard

### LINKED ISSUE #321: Android application fails to launch with attach 4.0.15
We have an Android application that we're building with `graalvm-svm-java17-linux-gluon-22.1.0.1-Final` JavaFX 18.0.2, charm glisten 6.1.1, and glisten afterburner 2.1.0.

The app works fine with attach+gluonfx maven plugin 4.0.14, but it fails to make it to the gluon splash screen on 4.0.15. We've tested it on a Pixel 4a running Android 13 and a Samsung Galaxy S20 running Android 11.

Under 4.0.14, this sequence happens the first time the application is launched:
* Popup requests permission to access photos, videos, music, and audio on this device (I think this is actually requesting storage permission)
* Popup requests access to location (for bluetooth)
* If bluetooth is not on, requests permission to turn it on
* Main screen + gluon splash screen shows.

On subsequent runs, it goes straight to the main screen + splash screen.

Under 4.0.15, this sequence happens the first time the application is launched:
* Popup requests permission to access photos, videos, music, and audio on this device (I think this is actually requesting storage permission)
* The application window disappears (app crashes)

In the console output, this appears when it crashes:
```
[Thu Aug 18 17:43:37 EDT 2022][INFO] [SUB] --------- beginning of crash
[Thu Aug 18 17:43:37 EDT 2022][INFO] [SUB] E/AndroidRuntime( 5773): FATAL EXCEPTION: main
[Thu Aug 18 17:43:37 EDT 2022][INFO] [SUB] E/AndroidRuntime( 5773): Process: com.soartech.isaacuserui, PID: 5773
[Thu Aug 18 17:43:37 EDT 2022][INFO] [SUB] E/AndroidRuntime( 5773): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
[Thu Aug 18 17:43:37 EDT 2022][INFO] [SUB] E/AndroidRuntime( 5773):     at com.gluonhq.helloandroid.Util$1$1.run(Util.java:90)
[Thu Aug 18 17:43:37 EDT 2022][INFO] [SUB] E/AndroidRuntime( 5773):     at android.os.Handler.handleCallback(Handler.java:883)
[Thu Aug 18 17:43:37 EDT 2022][INFO] [SUB] E/AndroidRuntime( 5773):     at android.os.Handler.dispatchMessage(Handler.java:100)
[Thu Aug 18 17:43:37 EDT 2022][INFO] [SUB] E/AndroidRuntime( 5773):     at android.os.Looper.loop(Looper.java:237)
[Thu Aug 18 17:43:37 EDT 2022][INFO] [SUB] E/AndroidRuntime( 5773):     at android.app.ActivityThread.main(ActivityThread.java:8034)
[Thu Aug 18 17:43:37 EDT 2022][INFO] [SUB] E/AndroidRuntime( 5773):     at java.lang.reflect.Method.invoke(Native Method)
[Thu Aug 18 17:43:37 EDT 2022][INFO] [SUB] E/AndroidRuntime( 5773):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
[Thu Aug 18 17:43:37 EDT 2022][INFO] [SUB] E/AndroidRuntime( 5773):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
[Thu Aug 18 17:43:37 EDT 2022][INFO] [SUB] W/ActivityManager( 1191): crash : com.soartech.isaacuserui,0
[Thu Aug 18 17:43:37 EDT 2022][INFO] [SUB] W/ActivityManager( 1191): setHasOverlayUi called on unknown pid: 5773
```

Very rarely, the application actually makes it to asking for the location permission (but then the app window disappears), and at least twice today it actually made it to the main screen + splash screen. It appeared to work correctly if it made it that far.

I saw in https://github.com/gluonhq/attach/commit/39d89f7141f97df8ea1d3fd12bf579b6de7b3718 that attach is now targeting platform 30. Our app is only targeting 29, so I updated our manifest to point to 30, but it made no difference.

Unfortunately I can't share the code or the complete logs, but our manifest is below if that helps. I can potentially pull out specific parts of the logs if that would be helpful -- just tell me what to look for.

I should also say, the even with 4.0.15, the app works fine on Windows.

Here's our AndroidManifest.xml:
```xml
<?xml version='1.0'?>
<manifest xmlns:android='http://schemas.android.com/apk/res/android' package='com.soartech.isaacuserui' android:versionCode='1' android:versionName='1.0'>
	<uses-sdk android:minSdkVersion="29"
			  android:targetSdkVersion="29" />
    <supports-screens android:xlargeScreens="true"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>

    <application android:label='ISAAC' android:icon="@mipmap/ic_launcher"
                 android:theme="@style/IsaacTheme"
                 android:requestLegacyExternalStorage="true"
    >
        <activity android:name='com.gluonhq.helloandroid.MainActivity'
                  android:configChanges="orientation|keyboardHidden"
                  android:screenOrientation="landscape"
                  android:fitsSystemWindows="true"
        >
             <intent-filter>
                <category android:name='android.intent.category.LAUNCHER'/>
                <action android:name='android.intent.action.MAIN'/>
             </intent-filter>
        </activity>
        <activity android:name='com.gluonhq.helloandroid.PermissionRequestActivity'/>
    </application>
</manifest>
```

### PR DESCRIPTION
**Pull request by jperedadnr**
Fixes #321

### CODE REVIEW

File: modules/util/src/main/native/android/dalvik/Util.java [hunk 1]
```diff
@@ -41,14 +41,18 @@ public class Util {
     public static final String TAG = "GluonAttach";
 
     private static Activity activity;
+    private static ClipboardManager clipboard;
     private static IntentHandler intentHandler;
     private static LifecycleEventHandler lifecycleEventHandler;
     private static boolean debug = false;
 
     public Util(Activity activity) {
         this.activity = activity;
```
Comment (johanvos) [inline modules/util/src/main/native/android/dalvik/Util.java]: activity is static

**Review by johanvos — APPROVED** [review]
