### PR TITLE
Fix No fine (GPS) position on Android anymore

### LINKED ISSUE #222: No fine (GPS) position on Android anymore
For some time now I don't get the PositionService working anymore, so that it would provide me with periodic position updates from GPS. When I start the service I get one position and that's it. Also the GPS symbol, which normally appears in the status bar for any app which activates GPS, does not show up anymore. I have provided a slightly modified HelloGluon version which should show the issue. This behaviour is consistent on all my devices and I even made sure that they had a valid GPS fix before I started the test. I even provided my own AndroidManifest.xml file (is that actually still necessary?) requesting coarse and fine location, but it did not change anything. So what is going on here? I tested this with client-maven-plugin 0.1.33 as well as 0.1.34-SNAPSHOT and Attach 4.0.9 as well as 4.0.10-SNAPSHOT on my Samsung tablet (Android 10) and phone (Android 8).
[HelloGluon.zip](https://github.com/gluonhq/attach/files/5453502/HelloGluon.zip)

### PR DESCRIPTION
**Pull request by mipastgt**
Fixes #222 No fine (GPS) position on Android anymore

Due to the || operator the check of the fine location was skipped here.

### CODE REVIEW

File: modules/position/src/main/native/android/dalvik/DalvikPositionService.java [hunk 1]
```diff
@@ -79,7 +79,7 @@ public DalvikPositionService(Activity activity) {
         if (debug) {
             Log.v(TAG, "Construct DalvikPositionService");
         }
-        boolean gpsEnabled = Util.verifyPermissions(Manifest.permission.ACCESS_COARSE_LOCATION) || 
+        boolean gpsEnabled = Util.verifyPermissions(Manifest.permission.ACCESS_COARSE_LOCATION) | // Don't use || here!
```
Comment (jperedadnr) [inline modules/position/src/main/native/android/dalvik/DalvikPositionService.java]: I'd rather prefer a comment like:
```
// Both permissions require to be verified
```

Comment (mipastgt) [reply modules/position/src/main/native/android/dalvik/DalvikPositionService.java]: Changed comment as requested.

**Review by johanvos — APPROVED** [review]
good catch

File: modules/position/src/main/native/android/dalvik/DalvikPositionService.java [hunk 2]
```diff
@@ -79,7 +79,7 @@ public DalvikPositionService(Activity activity) {
         if (debug) {
             Log.v(TAG, "Construct DalvikPositionService");
         }
-        boolean gpsEnabled = Util.verifyPermissions(Manifest.permission.ACCESS_COARSE_LOCATION) || 
+        boolean gpsEnabled = Util.verifyPermissions(Manifest.permission.ACCESS_COARSE_LOCATION) | // Both permissions require to be verified
```
Comment (jperedadnr) [inline modules/position/src/main/native/android/dalvik/DalvikPositionService.java]: On a second thought, this might be better (to avoid future confusions):
```
// Verify both permissions
boolean coarseEnabled = Util.verifyPermissions(Manifest.permission.ACCESS_COARSE_LOCATION);
boolean fineEnabled = Util.verifyPermissions(Manifest.permission.ACCESS_FINE_LOCATION);
boolean gpsEnabled = coarseEnabled || fineEnabled;
```
Would you mind changing it?

Comment (mipastgt) [reply modules/position/src/main/native/android/dalvik/DalvikPositionService.java]: No, I actually had the same idea but just did not want to change too much. Just pushed the changes.

**Review by jperedadnr — APPROVED** [review]
